version: 1.0.1-BETA
author: MauriceLPs
name: LotusGamingSystem
main: eu.lotusgc.mc.main.Main
api-version: 1.21
depend: [ProtocolLib, LuckPerms]

commands:
    s:
    profile:
    gamemode:
        aliases: gm
    cc:
        aliases: chatclear
    invsee:
    sethome:
    listhomes:
    delhome:
    home:
    time:
    msg:
    msgopt:
    r:
    fly:
    workbench:
        aliases: wb
    weather:
    sb:
    clearlag:
    afk:
    setspawn:
    spawn:
    tp:
    tphere:
    tpall:
    gc:
    backpack:
        aliases: bp
	onlinemap:
		aliases: map